### ISSUE TITLE
database creation with api namespace is missing

### ISSUE THREAD

**Issue by coutouly** [fiskaly/grafana.surrealdb#11]
when i try to create a database with the api of grafana namespace is missing.
i send this json:
`{'name': 'Surrealdb', 'type': 'fiskaly-surrealdb-datasource', 'typeName': 'SurrealDB', 'url': 'surrealdb:8000', 'access': 'proxy', 'withCredentials': False, 'basicAuth': False, 'jsonData': {'database': 'test', 'location': 'surrealdb:8000', 'namespace': 'test', 'username': 'root', 'password': 'root'}, 'uid': 'surrealdb', 'isDefault': True, 'database': 'fiskaly-surrealdb-datasource'}`
a this end point:
POST /api/datasources
when i login and show the new database i get this:
![image](https://github.com/fiskaly/grafana.surrealdb/assets/7043117/94a261fc-c2c1-4ec0-a5c9-c0ff323563e3)
the namespace is missing .
can you test it and verify.
thanks

**Comment by ppaulweber** [comment]
@coutouly if you are using the provisioning based datasource configuration of the SurrealDB namespace property is called `nameaddr` in the low-level configuration. This repository us using an example YAML-based provisioning as follows:

https://github.com/fiskaly/grafana.surrealdb/blob/f1681f35603219b882e10dd76c70aed9ef81d26b/etc/provisioning/datasources/default.yaml#L1-L18

Therefore, your JSON payload should be something like this for the Grafana API:

```
{ 'name': 'Surrealdb'
, 'type': 'fiskaly-surrealdb-datasource'
, 'uid': 'surrealdb'
, 'isDefault': true
, 'jsonData':
  { 'location': 'surrealdb:8000'
  , 'database': 'test'
  , 'nameaddr': 'test'
  , 'username': 'root'
  }
, 'secureJsonData':
  { 'password': 'root'
  }
}
```

The `url` and `basicAuth` fields are not part of this plugin, see https://github.com/fiskaly/grafana.surrealdb/blob/master/src/README.md#configuration.

Furthermore, I would recommend not to use the `root` user for data source connections as stated in the documentation, see: 

https://github.com/fiskaly/grafana.surrealdb/blob/f1681f35603219b882e10dd76c70aed9ef81d26b/src/README.md?plain=1#L18-L19

Please let me know if it works with the updated configuration JSON payload.

**Comment by ppaulweber** [comment]
@coutouly any updates on this issue from your side or did it work now by providing the JSON field `nameaddr` instead of `namespace` in the API call?

**Comment by coutouly** [comment]
it s ok everithing works
thank you
