### ISSUE TITLE
timestamp in query

### ISSUE THREAD

**Issue by coutouly** [fiskaly/grafana.surrealdb#12]
Hello ,
i create a timeserie:
```
{
    "id": "timetable:03jl9sgvaey8b2bh53tq",
    "location": "location:361820095V6",
    "person": "person:CLEA",
    "timestamp": "2024-02-22 21:41:01.123333"
}
or
{
    "id": "timetable:03jl9sgvaey8b2bh53tq",
    "location": "location:361820095V6",
    "person": "person:CLEA",
    "timestamp": "2024-02-22T21:41:01.123333"
}
```
i want to view it on grafana but the field timestamp doesnt work for date selection
and i cant see it in table mode:
![image](https://github.com/fiskaly/grafana.surrealdb/assets/7043117/7a865d09-9a28-4c42-b5be-f9c1c7148249)

the field timestamp is empty.
even if i choose timeseries ...
![image](https://github.com/fiskaly/grafana.surrealdb/assets/7043117/29c38477-22e6-4ab7-b28a-b922e5d11a81)
the timerange doesnt affect the result
![image](https://github.com/fiskaly/grafana.surrealdb/assets/7043117/acd5cdce-999a-4c88-9b55-a1a36e227822)

is there a specific way to save timestamp ? what form ?
thanks in advance
lucile

**Comment by coutouly** [comment]
i change the timestamp and i see in the table the date .
it is ok
but the range selection do not work
do i have to write it in the query ?
thanks
![image](https://github.com/fiskaly/grafana.surrealdb/assets/7043117/60b97809-8e33-4d09-8743-cf0824e62499)

**Comment by ppaulweber** [comment]
@coutouly yes you can dynamically adapt the query with the provided datasource variables as described at: https://github.com/fiskaly/grafana.surrealdb/tree/master/src#design

If you have e.g. a timestamp field you could use the `where` clause of `SurrealQL`:
```
select timestamp, data from table where timestamp >= $from and timestamp <= $to
```

If you would have e.g. a timeseries-based record ID table in `SurrealDB` you could do:
```
select timestamp, data from table:[$from]..[$to]
```

PS: can you provide me some feedback on your other issue as well? thx :pray:

**Comment by coutouly** [comment]
hello,
I try to use $from but it's not working could you please be more accurate.
thanks

**Comment by coutouly** [comment]
so it works with:

`select timestamp,person.prenom as prenom ,geo::hash::encode(location.location) as loc from timetable where time::millis(timestamp) >= $__from and time::millis(timestamp) <= $__to and  person.prenom = '$prenom'   fetch location; `

**Comment by ppaulweber** [comment]
@coutouly I'm happy it works now for you ... so it was just an issue of the actual query writing.

Regarding the variables `$from`, `$to`, and `$now`: those are built-in variables provided by the backend implementation of the data source which you can use for your query building as well and they are more specialized for the use-case of timeseries querying. More information is provided in https://github.com/fiskaly/grafana.surrealdb/tree/master/src#design.
