### ISSUE TITLE
Provide Dashboard Variable Query Support

### ISSUE THREAD

**Issue by coutouly** [fiskaly/grafana.surrealdb#6]
It miss thé Query SQL  for variable.

**Comment by ppaulweber** [comment]
Dear @coutouly, do you refer to the variable deduction of the Grafana variables? Because the templating of all the scope variables is implemented in the data source backend.

Can you describe your issue in more detail?

**Comment by coutouly** [comment]
In the dashboard WE Can create variable in grafana by queriing thé dattabase.
In a surrealdb dashboard when creating a variable with a Query it IS ont possible to write thé Query

**Comment by ppaulweber** [comment]
@coutouly can you clarify what in your context a "surrealdb dashboard" is? Best would be maybe to follow-up on this issue if you can provide some screenshots or a screen recording showcasing the situation.

**Comment by coutouly** [comment]
when i create a variable in the dashboard i want to use a query:
![image](https://github.com/fiskaly/grafana.surrealdb/assets/7043117/af5ad2db-4c89-4149-a7dd-2758585dab6c)
but i dont know where to write the query ???
do you understand what i mean .

**Comment by ppaulweber** [comment]
@coutouly thank you for this elaborate description and now I know what the exact issue is ... I've already started to implement this functionality where you can then have an additional query field to write `SurrealQL` to query the contents of the defined variable.

I'll update you ASAP the functionality is implemented.

**Comment by coutouly** [comment]
I am very happy that you do the job for us. Becaus i love surrealdb and use alors grafana.
Thanks in advence.

**Comment by ppaulweber** [comment]
@coutouly the feature is already implemented and tested ... I've already started the release process and depending on the publishing process (reviewing etc.) the version `v0.3.0` [1] of the plugin should be available soon in the Grafana plugin catalog [2] which includes than the **Variable Query** support. You can already have a look at the documentation [3] or in the following screencast to see how it works:

[1] https://github.com/fiskaly/grafana.surrealdb/releases/tag/v0.3.0
[2] https://grafana.com/grafana/plugins/fiskaly-surrealdb-datasource/
[3] https://github.com/fiskaly/grafana.surrealdb/blob/v0.3.0/src/README.md#variable-query

![variable-query](https://github.com/fiskaly/grafana.surrealdb/assets/6830431/ec84cade-49ac-49d4-9479-323429641ee3)

**Comment by ppaulweber** [comment]
FYI: @coutouly version `v0.3.0` with the *Variable Query* support was just published in the Grafana plugin catalog, see: https://grafana.com/grafana/plugins/fiskaly-surrealdb-datasource

Please have a look and if possible provide some feedback :relaxed:

**Comment by coutouly** [comment]
Hello, I try the variable editor and it works great.
thank you.
